# at this point docker use the directory name "appbto" as a prefix
  #docker-compose -p myproject up
  #the upper comment changes the prefix to myproject

version: "3.9" # redundant: stating the version is not necessary for recent version of docker-compose

services:
  database:
    build:
      context: ./database
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pern_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5000"
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pern_db
    depends_on:
      - database
    command: ["bash", "./wait-for-it.sh", "database:5432", "--", "npm", "start"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    depends_on:
      - backend

volumes:
  db_data:
