# at this point docker use the directory name "appbto" as a prefix
  #docker-compose -p myproject up
  #the upper comment changes the prefix to myproject

version: "3.9" # redundant: stating the version is not necessary for recent version of docker-compose

services:
  database:
    build:
      context: ./database
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pern_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pern_db
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    command: ["bash", "./wait-for-it.sh", "database:5432", "--", "npm", "start"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
